apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app.kubernetes.io/name: poker-api
  app.kubernetes.io/component: java
  app.kubernetes.io/instance: default

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
